
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 05 23:51:47 IRDT 2019
//----------------------------------------------------

package cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BOOL = 13;
  public static final int GT = 70;
  public static final int CONST = 20;
  public static final int PREMINMIN = 53;
  public static final int BOOL_CONST = 5;
  public static final int PLUSEQ = 27;
  public static final int UNTIL = 43;
  public static final int SIZEOF = 48;
  public static final int COMMA = 25;
  public static final int LT = 71;
  public static final int PREPLUSPLUS = 54;
  public static final int DOUBLE = 17;
  public static final int STRING_CONST = 9;
  public static final int NOT = 74;
  public static final int TILDE = 52;
  public static final int FLOAT = 14;
  public static final int SEMCOLON = 41;
  public static final int RECORD = 21;
  public static final int EQ = 26;
  public static final int MOD = 61;
  public static final int REAL_CONST = 8;
  public static final int LONG = 15;
  public static final int PLUS = 57;
  public static final int CHAR = 16;
  public static final int SWITCH = 33;
  public static final int UMIN = 65;
  public static final int FOR = 40;
  public static final int VOID = 19;
  public static final int EXTERN = 2;
  public static final int DIV = 60;
  public static final int RETURN = 22;
  public static final int MULT = 59;
  public static final int INT_CONST = 4;
  public static final int ELSE = 32;
  public static final int MINMIN = 55;
  public static final int BREAK = 23;
  public static final int GTEQ = 68;
  public static final int DOT = 51;
  public static final int INT = 12;
  public static final int EQEQ = 66;
  public static final int EOF = 0;
  public static final int ARITAND = 62;
  public static final int DEFAULT = 38;
  public static final int FUNCTION = 3;
  public static final int MULTEQ = 29;
  public static final int REPEAT = 42;
  public static final int MINUS = 58;
  public static final int LTEQ = 69;
  public static final int IN = 45;
  public static final int OR = 73;
  public static final int error = 1;
  public static final int CHAR_CONST = 7;
  public static final int CLOSEPAR = 47;
  public static final int DIVEQ = 30;
  public static final int ARITOR = 63;
  public static final int CONTINUE = 24;
  public static final int IF = 31;
  public static final int ID = 10;
  public static final int OF = 34;
  public static final int END = 37;
  public static final int COLON = 35;
  public static final int INEQ = 67;
  public static final int FOREACH = 44;
  public static final int LONG_CONST = 6;
  public static final int BEGIN = 36;
  public static final int CASE = 39;
  public static final int PLUSPLUS = 56;
  public static final int OPENBRAC = 49;
  public static final int STRING = 18;
  public static final int CLOSEBRAC = 50;
  public static final int AND = 72;
  public static final int OPENPAR = 46;
  public static final int AUTO = 11;
  public static final int XOR = 64;
  public static final int MINUSEQ = 28;
}

